### ISSUE TITLE
Hint in wrong place when passing the string concatenation as parameter

### ISSUE THREAD

**Issue by ljubadr** [bzrncev/intellij-parameter-hints#4]
Hi, first of all I wanted to thank you for making this nice extension. I just started using it, and it looks really nice!

I noticed a bug when I pass the concatenated string to a function/method - hint is placed in wrong position

Here is the minimal example to recreate the bug, and I've attached the screenshot of the result

```
<?php

function test($text)
{
  return $text;
}

test('a'.'b');          // works
test('a'.'b'.'c');      // hint after `'a'`
test('a'.'b'.'c'.'d');  // hint after `'b'`
```
Here is the result:
![Selection_018](https://user-images.githubusercontent.com/13367907/82161950-e8560f00-986e-11ea-8262-6d40ab937c0d.png)

**Expected result:** `text:` is always at the beginning
**Actual result** `text:` is inserted between the concatenated string

Let me know if you need any additional info

**Comment by bzrncev** [comment]
Hi, you are welcome. Thanks for reporting this bug, it is now fixed with #5 .

**Comment by bzrncev** [comment]
<img width="838" alt="Screen Shot 2020-05-18 at 2 52 18 AM" src="https://user-images.githubusercontent.com/8425966/82164793-ae0e6100-98b2-11ea-97a2-1420cd55cb95.png">

**Comment by ljubadr** [comment]
Thank you for this quick update!

I can confirm that it's fixed now
