### ISSUE TITLE
slow loading plugin

### ISSUE THREAD

**Issue by helioh3** [bzrncev/intellij-parameter-hints#6]
I love the plugin. But when I click on the file I see slowness to load the parameters hints. It's bug?

**Comment by bzrncev** [comment]
There is a delay because Intelephense must be loaded, then parsing the files etc. 

Liam Hammett made a new extension [https://marketplace.visualstudio.com/items?itemName=liamhammett.inline-parameters](url) which has faster parsing time, so you should check it out.
